In [1]:
import numpy as np

print(np.arange(1,50,1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [58]:
import numpy as np

arr = np.random.randint(1, 51,12).reshape(3,4)
print(arr)
print("Mean: ", np.mean(arr))
print("Median: ",np.median(arr))
print("Standard Deviation: ",np.std(arr))
print("Total Sum", np.sum(arr))
print("Row Sum", np.sum(arr, axis =1))
print("Reshaped: ",arr.reshape((2,6)))


[[18 16 46 19]
 [48 37 18 23]
 [36 14 38  5]]
Mean:  26.5
Median:  21.0
Standard Deviation:  13.282193593931186
Total Sum 318
Row Sum [ 99 126  93]
Reshaped:  [[18 16 46 19 48 37]
 [18 23 36 14 38  5]]


In [67]:
import time

# Record the start time
start_time = time.time()

x = np.arange(1,10).reshape(3,3)
y = np.arange(10,19).reshape(3,3)
print(f"Sum: {x+y}\nDiff: {x-y}\nDot-Prod: {np.dot(x,y)}\nElement-Multiply: {x*y}\nDivision: {x/y}\nTranpose M1: {x.T}\nTranspose M2: {y.T}" )
print(f"Det of m1:{np.linalg.det(y)}, Det of m2: {np.linalg.det(x)}")
if np.linalg.det(x) != 0: 
    print("Inverse of m1:\n", np.linalg.inv(x)) 
else: 
    print("Matrix 1 is not invertible")
if np.linalg.det(y) != 0: 
    print("Inverse of m2:\n", np.linalg.inv(y)) 
else: 
    print("Matrix 2 is not invertible")
elapsed_time = time.time() - start_time
print(elapsed_time)

Sum: [[11 13 15]
 [17 19 21]
 [23 25 27]]
Diff: [[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
Dot-Prod: [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
Element-Multiply: [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
Division: [[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
Tranpose M1: [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose M2: [[10 13 16]
 [11 14 17]
 [12 15 18]]
Det of m1:0.0, Det of m2: -9.51619735392994e-16
Inverse of m1:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
Matrix 2 is not invertible
0.0010061264038085938


In [66]:
%timeit z = np.zeros(x.shape)


242 ns ± 17.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
